version: "3"

services:
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    volumes:
      - db_storage:/var/lib/mysql
      - ./src/VerifyBot/VerifyBot/DBSchema/verifyBot.sql:/docker-entrypoint-initdb.d/verifyBot.sql

  bot:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./public.pem:/app/public.pem

volumes:
  db_storage:

