version: "3"

services:
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql

  bot:
    build: .
    env_file:
      - .env
    restart: always
    depends_on:
      - db

volumes:
  storage:

